### ISSUE TITLE
The game isn't starting up

### ISSUE THREAD

**Issue by BalintXHD** [Akrivus/Amalgam#10]
Game Output:

[17:38:51] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:38:51] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:38:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:38:51] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2796 for Minecraft 1.12.2 loading
[17:38:51] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_191, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_191
[17:38:51] [main/INFO] [FML]: Searching C:\Users\Bálint\AppData\Roaming\.minecraft\mods for mods
[17:38:51] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E2.jar
[17:38:51] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:38:51] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[17:38:51] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:38:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:38:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:38:51] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[17:38:51] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[17:38:51] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[17:38:51] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[17:38:51] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\Bálint\AppData\Roaming\.minecraft\mods\OptiFine_1.12.2_HD_U_E2.jar
[17:38:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:38:55] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:38:56] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:38:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:38:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:38:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:38:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:38:57] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[17:38:57] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:38:59] [main/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[17:38:59] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[17:38:59] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: java.lang.ExceptionInInitializerError
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraftforge.common.ForgeHooks.<clinit>(ForgeHooks.java:324)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.Class.forName0(Native Method)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.Class.forName(Unknown Source)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.getTargetClass(ReflectorClass.java:47)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.<init>(ReflectorClass.java:26)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.<init>(ReflectorClass.java:17)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:264)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.renderer.vertex.DefaultVertexFormats.<clinit>(DefaultVertexFormats.java:16)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraftforge.client.ForgeHooksClient$LightGatheringTransformer.<clinit>(ForgeHooksClient.java:599)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraftforge.client.ForgeHooksClient.<clinit>(ForgeHooksClient.java:642)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:335)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:39:02] [main/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:39:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.RuntimeException: Accessed Items before Bootstrap!
[17:39:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.init.Items.<clinit>(SourceFile:9)
[17:39:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 18 more
[17:39:03] [main/WARN] [Config]: [OptiFine] (Reflector) More than one method found: net.minecraft.potion.Potion.renderHUDEffect
[17:39:03] [main/WARN] [Config]: [OptiFine] (Reflector)  - public void net.minecraft.potion.Potion.renderHUDEffect(int,int,net.minecraft.potion.PotionEffect,net.minecraft.client.Minecraft,float)
[17:39:03] [main/WARN] [Config]: [OptiFine] (Reflector)  - public void net.minecraft.potion.Potion.renderHUDEffect(net.minecraft.potion.PotionEffect,net.minecraft.client.gui.Gui,int,int,float,float)
[17:39:03] [main/INFO] [Config]: [OptiFine] *** Reflector Vanilla ***
[17:39:04] [Client thread/INFO] [minecraft/Minecraft]: Setting user: BalintX
[17:39:07] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.init.Items
	at net.minecraft.potion.PotionHelper.func_185207_a(PotionHelper.java:154) ~[akh.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:504) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [17:39:07] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[17:39:07] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[17:39:07] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[17:39:07] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[17:39:07] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[17:39:07] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[17:39:07] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by Akrivus** [comment]
The log you provided says this is a crash caused by Optifine. Send me a list of mods you have. Until then, I can only suggest that you should update Forge (if you haven't already), and update Optifine.

**Comment by BalintXHD** [comment]
amalgam10n10
craftstudio
journeymap
kagic
mcjitylib
minions
optifine

**Comment by BalintXHD** [comment]
Okay, the problem was Optifine. I think this is solved.
